server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # SPA: send everything to index.html (except existing files)
  location / {
    try_files $uri $uri/ /index.html;
  }

  # cache static assets
  location /assets/ {
    try_files $uri =404;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}
