partOf: "exos-simulator"

replicaCount: 1

service:
  type: LoadBalancer
  port: 80

containerPort: 80

resources:
  requests:
    cpu: "25m"
    memory: "96Mi"
  limits:
    cpu: "150m"
    memory: "192Mi"
